### ISSUE TITLE
'nullptr' was not declared in this scope

### ISSUE THREAD

**Issue by leafjungle** [wanadev/pyguetzli#1]
When I try to "pip install pyguetzli", I got:
'nullptr' was not declared in this scope

And I see the compiler options:
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -I. -IInclude -I./Include -O2 -pipe -fPIC -I/tmp/pip-build-mGtYG5/pyguetzli/pyguetzli -I/tmp/pip-build-mGtYG5/pyguetzli/pyguetzli/../guetzli -I/home/img/.jumbo/include/python2.7 -c build/temp.linux-x86_64-2.7/pyguetzli._guetzli.cpp -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/pyguetzli._guetzli.o

After googling, I was told to use "-std=c++11" opiton.  But how can I do it ?

**Comment by flozz** [comment]
Hello,

you can set this flag through an environment variable:

    CPPFLAGS="--std=c++11" pip install pyguetzli

We will try to force this flag when compiling Guetzli or to at least to document this :)

**Comment by flozz** [comment]
This flag is now set by default when building Guetzli during the installation process of PyGuetzli (released in v1.0.1). I also documented the issue in the README.

**Comment by flozz** [comment]
I close this issue, please re-open it if you still have problem :)
