### ISSUE TITLE
Linker issue

### ISSUE THREAD

**Issue by stefanvdw1** [wanadev/pyguetzli#2]
Hi,

I have successfully installed pyguetzli using the PIP methoded outlined here: [https://pypi.python.org/pypi/pyguetzli](url) but unfortunately when running a simple script in PyCharm I get the following error:

`ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib‌​/python3.6/site-pack‌​ages/pyguetzli/_guet‌​zli.abi3.so, 2): Symbol not found: __ZN7guetzli7ProcessERKNS_6ParamsEPNS_12ProcessStatsERKSsPSs Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python‌​3.6/site-packages/py‌​guetzli/_guetzli.abi‌​3.so Expected in: flat namespace in /Library/Frameworks/Python.framework/Versions/3.6/lib/python‌​3.6/site-packages/py‌​guetzli/_guetzli.abi‌​3.so`

I've tried reinstalling, reinstalling using homebrew and reinstalling using the PyCharm, but this all yielded the same result.

**Comment by flozz** [comment]
Hello,

I tried various installation methods on on a Mac and it worked

```
$ sudo pip install pyguetzli
$ python
>>> import pyguetzli
```

After some research, I found this thread on stackoverflow that may help: https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

**Comment by stefanvdw1** [comment]
It does explain the issue but does not really offer an easy solution to use this library unfortunately. 

Thank you for your help anyway!

**Comment by flozz** [comment]
Maybe you can try to define the `PYTHONPATH` environment variable with the path to the python libs installed by brew:

```
PYTHONPATH=/usr/local/lib/python3.6/site-packages   /path/to/pycharm
```

**Comment by Breush** [comment]
@stefanvdw1 Any update? Did that work?

**Comment by flozz** [comment]
I close this issue as there is no response. Please reopen it if you have update.
