### ISSUE TITLE
Build failing on Windows

### ISSUE THREAD

**Issue by TheZoc** [wanadev/pyguetzli#3]
Hello,

Today I attempted to install pyguetzli on Python3.6.4, on Windows 10

I saved the console output: [pyguetzli.txt](https://github.com/wanadev/pyguetzli/files/1765342/pyguetzli.txt)

I also get the error:
```
Failed building wheel for pyguetzli

Command "e:\development\github\havenweb\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Zoc\\AppData\\Local\\Temp\\pip-build-htfgs80j\\pyguetzli\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Zoc\AppData\Local\Temp\pip-icil3s3g-record\install-record.txt --single-version-externally-managed --compile --install-headers e:\development\github\havenweb\venv\include\site\python3.6\pyguetzli" failed with error code 1 in C:\Users\Zoc\AppData\Local\Temp\pip-build-htfgs80j\pyguetzli\
```

Apparently the first error message is related to this:
```
  LINK : fatal error LNK1181: cannot open input file 'C:\Users\Zoc\AppData\Local\Temp\pip-build-htfgs80j\pyguetzli\pyguetzli\..\guetzli\bin\Release\libguetzli_static.a'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181
```

I hope this helps! :)

**Comment by flozz** [comment]
Hi,

pyguetzli was not initially designed to be compiled on MS Windows, that's why it does not work. I am rewriting the build process to make it work on any platforms and I already built pyguetzli successfully on Windows:

 https://github.com/wanadev/pyguetzli/commit/4ea6b4f3fcf1b53264e67d891d9ab6def962600a

I will release a new version as soon as finish to clean my branch :)

**Comment by flozz** [comment]
**pyguetzli v1.0.4** released with MS Windows support :)
