### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by KorayTugberk-g** [wanadev/pyguetzli#6]
I have downloaded the Pyguetzli via pip install pyguetzli command. But I can't import it.

The error code below:

  File "c:/Users/Koray Tuğberk GÜBÜR/Desktop/python_all/Pillow/abc.py", line 1, in <module>
    import pyguetzli
ModuleNotFoundError: No module named 'pyguetzli'

**Comment by flozz** [comment]
Hello,

* What is you Python version?
* Have you encountered any error during the installation?
* Can you run the `pip install pyguetzli` command again and paste the output here?

:)

**Comment by flozz** [comment]
I close this issue as there is no response. Please reopen it if you need more help.
